#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Twig2React\Command\GenerateCommand;

require 'vendor/autoload.php';
require 'container.php';

$generate_service = $container->get('GenerateService');

$app = new Application('Twig2React', '1.0');
$app->add(new GenerateCommand($generate_service));

$app->run();


